# syntax=docker/dockerfile:1.4

FROM linkml/linkml AS builder

WORKDIR /app

COPY schema/ schema/
COPY md-templates/ md-templates/
COPY mkdocs.yml .

RUN pip install --no-cache-dir mkdocs linkml[mkdocs] mkdocs-material pymdown-extensions mkdocs-mermaid2-plugin
RUN gen-doc \
    --template-directory md-templates \
    --hierarchical-class-view \
    -d docs \
    schema/nuclei.yaml
RUN python3 -m mkdocs build

FROM scratch AS final
COPY --from=builder /app/site/ /
